spring:
  datasource:
    url: jdbc:mysql://localhost:3306/journal?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: springboot
    password: springboot
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false

  data:
    rest:
      base-path: /api